# Copy and paste these lines into your terminal to create issues:
# Make sure you are logged in with 'gh auth login' first.

gh issue create --title 'Buy Supplies:' --body 'Derived from PHASE 0: THE BAG BUILDER (Day 0 - Immediate)' --label 'status:backlog'
gh issue create --title 'Fill Folder A (Personal Identity):' --body 'Derived from PHASE 0: THE BAG BUILDER (Day 0 - Immediate)' --label 'status:backlog'
gh issue create --title 'Photocopy Joy'\''s Valid ID (Passport/UMID) x5.' --body 'Derived from PHASE 0: THE BAG BUILDER (Day 0 - Immediate)' --label 'status:backlog'
gh issue create --title 'Photocopy TIN ID x3.' --body 'Derived from PHASE 0: THE BAG BUILDER (Day 0 - Immediate)' --label 'status:backlog'
gh issue create --title 'Print Proof of Billing (Meralco/Water) x3.' --body 'Derived from PHASE 0: THE BAG BUILDER (Day 0 - Immediate)' --label 'status:backlog'
gh issue create --title 'Get 1x1 and 2x2 Photos (White Background) - Keep 10 copies.' --body 'Derived from PHASE 0: THE BAG BUILDER (Day 0 - Immediate)' --label 'status:backlog'
gh issue create --title 'Buy Community Tax Cert (Cedula) at Barangay Hall.' --body 'Derived from PHASE 0: THE BAG BUILDER (Day 0 - Immediate)' --label 'status:backlog'
gh issue create --title 'Fill Folder B (Investor Identity):' --body 'Derived from PHASE 0: THE BAG BUILDER (Day 0 - Immediate)' --label 'status:backlog'
gh issue create --title 'Print Color Scan of Brian'\''s Passport (Bio Page) x5.' --body 'Derived from PHASE 0: THE BAG BUILDER (Day 0 - Immediate)' --label 'status:backlog'
gh issue create --title 'Print Brian'\''s Specimen Signature Sheet x5.' --body 'Derived from PHASE 0: THE BAG BUILDER (Day 0 - Immediate)' --label 'status:backlog'
gh issue create --title 'Fill Folder C (Location):' --body 'Derived from PHASE 0: THE BAG BUILDER (Day 0 - Immediate)' --label 'status:backlog'
gh issue create --title 'Print Copy of Condo Title (CCT) / Deed of Sale for Marco Polo unit.' --body 'Derived from PHASE 0: THE BAG BUILDER (Day 0 - Immediate)' --label 'status:backlog'
gh issue create --title 'Action: Request "Certificate of No Objection" from Marco Polo PMO for "Home Office Use".' --body 'Derived from PHASE 0: THE BAG BUILDER (Day 0 - Immediate)' --label 'status:backlog'
gh issue create --title '08:00 AM Sync: Confirm "Cebu Loop Mobility Corp" as name.' --body 'Derived from PHASE 1: THE LEGAL SHIELD (Week 1 - The Sprint)' --label 'phase:1-legal-shield'
gh issue create --title '09:00 AM Online: Register name at SEC ESPARC (<https://esparc.secy.gov.ph>).' --body 'Derived from PHASE 1: THE LEGAL SHIELD (Week 1 - The Sprint)' --label 'phase:1-legal-shield'
gh issue create --title '01:00 PM Field: Visit Barangay Hall (Lahug).' --body 'Derived from PHASE 1: THE LEGAL SHIELD (Week 1 - The Sprint)' --label 'phase:1-legal-shield'
gh issue create --title '08:00 AM Sync: Verify Paid-Up Capital amount (₱625,000) is ready in Brian'\''s US Transferwise/Bank.' --body 'Derived from PHASE 1: THE LEGAL SHIELD (Week 1 - The Sprint)' --label 'phase:1-legal-shield'
gh issue create --title '09:00 AM Field: Go to UnionBank (Ayala/IT Park).' --body 'Derived from PHASE 1: THE LEGAL SHIELD (Week 1 - The Sprint)' --label 'phase:1-legal-shield'
gh issue create --title '06:00 PM Remote: Brian wires ₱625,000 to the new TITF account.' --body 'Derived from PHASE 1: THE LEGAL SHIELD (Week 1 - The Sprint)' --label 'phase:1-legal-shield'
gh issue create --title '08:00 AM Sync: Check if Wire Transfer arrived.' --body 'Derived from PHASE 1: THE LEGAL SHIELD (Week 1 - The Sprint)' --label 'phase:1-legal-shield'
gh issue create --title '09:00 AM Field: Go back to Bank.' --body 'Derived from PHASE 1: THE LEGAL SHIELD (Week 1 - The Sprint)' --label 'phase:1-legal-shield'
gh issue create --title '10:00 AM Admin: Notarize Treasurer'\''s Affidavit.' --body 'Derived from PHASE 1: THE LEGAL SHIELD (Week 1 - The Sprint)' --label 'phase:1-legal-shield'
gh issue create --title '01:00 PM Online: Finalize SEC Application.' --body 'Derived from PHASE 1: THE LEGAL SHIELD (Week 1 - The Sprint)' --label 'phase:1-legal-shield'
gh issue create --title '09:00 AM: Buy Domain `cebuloop.com` (Porkbun).' --body 'Derived from PHASE 1: THE LEGAL SHIELD (Week 1 - The Sprint)' --label 'phase:1-legal-shield'
gh issue create --title '10:00 AM: Setup Google Workspace (`joy@`, `brian@`).' --body 'Derived from PHASE 1: THE LEGAL SHIELD (Week 1 - The Sprint)' --label 'phase:1-legal-shield'
gh issue create --title '11:00 AM: Create "Cebu Loop Ops" Viber Group. Add Brian.' --body 'Derived from PHASE 1: THE LEGAL SHIELD (Week 1 - The Sprint)' --label 'phase:1-legal-shield'
gh issue create --title '09:00 AM Field: Visit BYD Cebu Dealership.' --body 'Derived from PHASE 1: THE LEGAL SHIELD (Week 1 - The Sprint)' --label 'phase:1-legal-shield'
gh issue create --title '01:00 PM Field: Scout Parking.' --body 'Derived from PHASE 1: THE LEGAL SHIELD (Week 1 - The Sprint)' --label 'phase:1-legal-shield'
gh issue create --title 'Monitor: Check email daily for SEC Payment Assessment.' --body 'Derived from PHASE 2: THE "PAPER HUB" (Weeks 2-6)' --label 'phase:2-paper-hub'
gh issue create --title 'Pay: Pay SEC Fees via GCash/Landbank.' --body 'Derived from PHASE 2: THE "PAPER HUB" (Weeks 2-6)' --label 'phase:2-paper-hub'
gh issue create --title 'Print: Receive Certificate of Incorporation. Add to Folder D.' --body 'Derived from PHASE 2: THE "PAPER HUB" (Weeks 2-6)' --label 'phase:2-paper-hub'
gh issue create --title 'BIR (Bureau of Internal Revenue):' --body 'Derived from PHASE 2: THE "PAPER HUB" (Weeks 2-6)' --label 'phase:2-paper-hub'
gh issue create --title 'Mayor'\''s Permit:' --body 'Derived from PHASE 2: THE "PAPER HUB" (Weeks 2-6)' --label 'phase:2-paper-hub'
gh issue create --title 'Bank Trip: With SEC Cert + BIR COR in hand.' --body 'Derived from PHASE 2: THE "PAPER HUB" (Weeks 2-6)' --label 'phase:2-paper-hub'
gh issue create --title 'Convert: Change TITF Account to Corporate Checking Account.' --body 'Derived from PHASE 2: THE "PAPER HUB" (Weeks 2-6)' --label 'phase:2-paper-hub'
gh issue create --title 'Access: Enroll Brian in Corporate Online Banking (Sole Approver).' --body 'Derived from PHASE 2: THE "PAPER HUB" (Weeks 2-6)' --label 'phase:2-paper-hub'
gh issue create --title 'Token: Request physical/digital token.' --body 'Derived from PHASE 2: THE "PAPER HUB" (Weeks 2-6)' --label 'phase:2-paper-hub'
gh issue create --title 'Software: Sign contract with RentCentric or Navotar (decide based on Decision Log).' --body 'Derived from PHASE 2: THE "PAPER HUB" (Weeks 2-6)' --label 'phase:2-paper-hub'
gh issue create --title 'Insurance: Secure "Passenger Personal Accident Insurance" (PPAI) quote for LTFRB.' --body 'Derived from PHASE 2: THE "PAPER HUB" (Weeks 2-6)' --label 'phase:2-paper-hub'
gh issue create --title 'Lease: If Marco Polo prohibits fleet parking, sign Lease Contract for small garage/lot (required for LTFRB).' --body 'Derived from PHASE 2: THE "PAPER HUB" (Weeks 2-6)' --label 'phase:2-paper-hub'
gh issue create --title 'Zoning: Get Zoning Clearance for the Garage location.' --body 'Derived from PHASE 2: THE "PAPER HUB" (Weeks 2-6)' --label 'phase:2-paper-hub'
gh issue create --title 'Wire: Brian sends Downpayment (20%) funds.' --body 'Derived from PHASE 3: ASSET COMMITMENT (Weeks 7-10)' --label 'phase:3-assets'
gh issue create --title 'Pay: Joy pays BYD Dealership.' --body 'Derived from PHASE 3: ASSET COMMITMENT (Weeks 7-10)' --label 'phase:3-assets'
gh issue create --title 'Order: Joy orders Teltonika GPS units online.' --body 'Derived from PHASE 3: ASSET COMMITMENT (Weeks 7-10)' --label 'phase:3-assets'
gh issue create --title 'Compile LTFRB Payload:' --body 'Derived from PHASE 3: ASSET COMMITMENT (Weeks 7-10)' --label 'phase:3-assets'
gh issue create --title 'Submit: Walk-in to LTFRB Region 7.' --body 'Derived from PHASE 3: ASSET COMMITMENT (Weeks 7-10)' --label 'phase:3-assets'
gh issue create --title 'Output: "Order of Payment" and "Notice of Hearing".' --body 'Derived from PHASE 3: ASSET COMMITMENT (Weeks 7-10)' --label 'phase:3-assets'
gh issue create --title 'Pickup: Receive 5 BYD Seagull units.' --body 'Derived from PHASE 3: ASSET COMMITMENT (Weeks 7-10)' --label 'phase:3-assets'
gh issue create --title 'Install: Technician installs Teltonika + Kill-switch.' --body 'Derived from PHASE 3: ASSET COMMITMENT (Weeks 7-10)' --label 'phase:3-assets'
gh issue create --title 'Sim: Insert Smart/Globe IoT Sims.' --body 'Derived from PHASE 3: ASSET COMMITMENT (Weeks 7-10)' --label 'phase:3-assets'
gh issue create --title 'Wrap: Car wrapping shop applies "Cebu Loop" decals.' --body 'Derived from PHASE 4: LAUNCH (Weeks 11-16)' --label 'phase:4-launch'
gh issue create --title 'Uniforms: Buy Polos and print Logos for Runners.' --body 'Derived from PHASE 4: LAUNCH (Weeks 11-16)' --label 'phase:4-launch'
gh issue create --title 'Train: Fleet Runners practice the "5-Star Clean" protocol.' --body 'Derived from PHASE 4: LAUNCH (Weeks 11-16)' --label 'phase:4-launch'
gh issue create --title 'Test: Dry run of App Booking -> Unlock -> Drive -> Return.' --body 'Derived from PHASE 4: LAUNCH (Weeks 11-16)' --label 'phase:4-launch'
gh issue create --title 'Go Live: Open App to public.' --body 'Derived from PHASE 4: LAUNCH (Weeks 11-16)' --label 'phase:4-launch'

# Successfully generated commands for 55 tasks.
